### ISSUE TITLE
Titles on mobile appear too large

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/blog#2]
The font for the titles is too large (breaking the title up at times)

**Comment by gdams** [comment]
![Uploading 80915590...]()

**Comment by gdams** [comment]
![image](https://user-images.githubusercontent.com/20224954/80915597-4224e800-8d4b-11ea-854a-8ae587fa3161.png)

**Comment by aahlenst** [comment]
Fixed via 609aba009179f379a83fbe73c5dfb18dacaccbc1
