### ISSUE TITLE
July 2020 Quarterly Patch Update Release Announcement

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/blog#210]
Issue to collect things to be mentioned in the release announcement.

**Comment by aahlenst** [comment]
ARM builds of 11+ fixed: https://github.com/AdoptOpenJDK/openjdk-support/issues/33

**Comment by gdams** [comment]
JFR in 8 is going to be a major enhancement.

**Comment by aahlenst** [comment]
Closed via #260.
