### ISSUE TITLE
April 2021 release announcement

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/blog#742]
Issue to collect topics for the next release announcement.

**Comment by aahlenst** [comment]
No more OpenJ9 XL: https://github.com/AdoptOpenJDK/openjdk-build/issues/2426

**Comment by aahlenst** [comment]
Symantec CA certificates removed: https://github.com/AdoptOpenJDK/openjdk-build/pull/2467

**Comment by pshipton** [comment]
For the mixed build change, see https://eclipse.github.io/openj9-docs/version0.25/#single-build-for-compressed-references-and-non-compressed-references
