### ISSUE TITLE
Linter on adoptopenjdk/blog fails to run

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/blog#785]
The linter check on adoptopenjdk/blog repository PR checking fails to run with dependency error:
`error Gatsby requires Node.js 12.13.0 or higher (you have v10.24.0)`

an example failure is here
https://github.com/AdoptOpenJDK/blog/pull/784/checks?check_run_id=2039964185

**Comment by aahlenst** [comment]
It's a blog problem. Gatsby nowadays wants at least NodeJS 12. So we've to update the PR checks and whatnot.

**Comment by tellison** [comment]
yes, understood.  I thought that updating the PR checks would be an infra task, but we can move this to the blog repository if you feel that is more appropriate

**Comment by tellison** [comment]
Fixed by https://github.com/AdoptOpenJDK/blog/pull/786
