### ISSUE TITLE
Update Linter GH Action to use Node 18

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/blog#937]
The Linter action is failing

**Comment by karianna** [comment]
@gdams I don't think a fix was landed?

**Comment by gdams** [comment]
This was fixed at Adoptium but I'm not interested in maintaining this repo. I'd actually propose that we archive it

**Comment by karianna** [comment]
Would a redirect be appropriate?  Or perhaps a single static page saying "Go there -->"?
